# Generated by Django 3.0.7 on 2020-10-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miaplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiapaciente',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
